frontend/.storybook/main.js, frontend/.storybook/preview.js, frontend/docs-index/_config.yml, frontend/docs-index/_layouts/default.html, frontend/docs-index/index.md, frontend/jsconfig.json, frontend/public/index.html, frontend/public/mockServiceWorker.js, frontend/src/fixtures/menuItemReviewFixtures.js, frontend/src/fixtures/temp.json, frontend/src/index.css, frontend/stryker.config.json
Closes issue #36. Followed ucsb dates fixture formatting.
=> MenuItemReviews Fixtures

frontend/src/fixtures/helpRequestFixtures.js
=> rg - added fixtures

frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js, frontend/src/stories/components/MenuItemReview/MenuItemReviewForm.stories.js, frontend/src/tests/components/MenuItemReview/MenuItemReviewForm.test.js
Closes issue #37. Form for MenuItemReview done and passing all tests. Tested on storybook as well.
Published story book link: [https://6726c65fac869bba81d3d68d-izcshjvznw.chromatic.com/?path=/docs/components-menuitemreview-menuitemreviewform--docs](url)
Screenshot of the new form:
=> VP menu item reviews form component

frontend/src/main/components/MenuItemReview/MenuItemReviewTable.js, frontend/src/main/utils/MenuItemReviewUtils.js, frontend/src/stories/components/MenuItemReview/MenuItemReviewTable.stories.js, frontend/src/tests/components/MenuItemReview/MenuItemReviewTable.test.js, frontend/src/tests/utils/MenuItemReviewUtils.test.js
Closes issue #38. Tested and working.
Link to published storybook below in comment:
=> VP MenuItemReviews Tables

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewCreatePage.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewEditPage.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewCreatePage.test.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewEditPage.test.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
Closes issue #39 . Working and tested. App has link for menuitemreviews and then create/edit
=> VP MenuItemReviews Placeholdrs

frontend/src/main/components/UCSBOrganization/UCSBOrganizationForm.js, frontend/src/stories/components/UCSBOrganization/UCSBOrganizationForm.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationForm.test.js
Resolves issue #19, please review the modified folders/files. Thank you in advance ^^.
Link to Storybook for UCSBOrganization Form: https://6726c65fac869bba81d3d68d-wmpimkuvuw.chromatic.com/?path=/docs/components-ucsborganization-ucsborganizationform--docs
Screenshot of UCSBOrganization Form:
=> Form Component for UCSBOrganization Finished, All Mutations Met

frontend/src/main/components/UCSBOrganization/UCSBOrganizationTable.js, frontend/src/main/utils/UCSBOrganizationsUtils.js, frontend/src/stories/components/UCSBOrganization/UCSBOrganizationTable.stories.js, frontend/src/tests/components/UCSBOrganization/UCSBOrganizationTable.test.js, frontend/src/tests/utils/UCSBOrganizationsUtils.test.js
Resolves Issue #20, please review the changes I made whenever y'all can. Thank you in advance!
Link to Storybook: https://6726c65fac869bba81d3d68d-wunxdlzlfl.chromatic.com/?path=/docs/components-ucsborganization-ucsborganizationtable--docs
Screenshot of Table Component for UCSBOrganizations:
=> Finish Table Component for UCSBOrganizations, All Mutations Met

frontend/src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js, frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationCreatePage.stories.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationCreatePage.test.js
Resolves Issue #22, whenever y'all have the chance to, please review my modifications made in `UCSBOrganizationCreatePage.js`, `UCSBOrganizationCreatePage.test.js` and a new file that was created, `UCSBOrganizationCreatePage.stories.js`. Thank you in advance!
Link to Storybook: https://6726c65fac869bba81d3d68d-colkzxblcw.chromatic.com/?path=/docs/pages-ucsborganization-ucsborganizationcreatepage--docs
Screenshot of Create Page for UCSBOrganization (fill in the text boxes, as well as the drop-down and then click Submit, you should get a little bubble that confirms you created the UCSBOrganization):
=> Finished UCSBOrganizations Create Page, All Mutations/Test are Met

frontend/src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js, frontend/src/stories/pages/UCSBOrganization/UCSBOrganizationIndexPage.stories.js, frontend/src/tests/pages/UCSBOrganization/UCSBOrganizationIndexPage.test.js
This PR resolves Issue #23, please review my modifications in `UCSBOrganizationIndexPage.js` (and it's respective test file) as well as `UCSBOrganizationIndexPage.stories.js` whenever y'all have the chance to! Thank you in advance. 
Link to Storybook: https://6726c65fac869bba81d3d68d-zehdhbjoll.chromatic.com/?path=/docs/pages-ucsborganization-ucsborganizationindexpage--docs
Screenshot of Index Page for UCSBOrganizations:
=> Finished UCSBOrganization Index Page, all tests are passing!

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationRequestForm.js, frontend/src/stories/components/RecommendationRequests/RecommendationRequestForm.stories.js, frontend/src/tests/components/RecommendationRequests/RecommendationRequestForm.test.js
closes #27 
closes #28 
Link to story book: https://6726c65fac869bba81d3d68d-hpbcojipoc.chromatic.com/?path=/docs/components-nav-appnavbar--docs
=> Added Recommendation Request form with tests 

frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationRequestForm.js, frontend/src/main/components/RecommendationRequests/RecommendationRequestTable.js, frontend/src/main/utils/recommendationRequestUtils.js, frontend/src/stories/components/RecommendationRequests/RecommendationRequestForm.stories.js, frontend/src/stories/components/RecommendationRequests/RecommendationRequestTable.stories.js, frontend/src/tests/components/RecommendationRequests/RecommendationRequestForm.test.js, frontend/src/tests/components/RecommendationRequests/RecommendationRequestTable.test.js, frontend/src/tests/utils/recommendationRequestUtils.test.js
closes #29
storybook line: https://6726c65fac869bba81d3d68d-iirwmcfizt.chromatic.com
=> Added table for Recommendation Request

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/RecommendationRequests/RecommendationRequestCreatePage.js, frontend/src/main/pages/RecommendationRequests/RecommendationRequestEditPage.js, frontend/src/main/pages/RecommendationRequests/RecommendationRequestIndexPage.js, frontend/src/tests/pages/RecommendationRequests/RecommendationRequestCreatePage.test.js, frontend/src/tests/pages/RecommendationRequests/RecommendationRequestEditPage.test.js, frontend/src/tests/pages/RecommendationRequests/RecommendationRequestIndexPage.test.js
closes #30
storybook link: https://6726c65fac869bba81d3d68d-sssztlzknq.chromatic.com/
=> Added Recommendation Request Page Placeholders

frontend/src/fixtures/helpRequestFixtures.js, frontend/src/main/components/HelpRequests/HelpRequestTable.js, frontend/src/main/utils/HelpRequestUtils.js, frontend/src/stories/components/HelpRequests/HelpRequestTable.stories.js, frontend/src/tests/components/HelpRequests/HelpRequestTable.test.js, frontend/src/tests/utils/HelpRequestUtils.test.js
=> rg - table for HelpRequests

frontend/src/main/components/MenuItemReview/MenuItemReviewForm.js, frontend/src/main/pages/MenuItemReview/MenuItemReviewIndexPage.js, frontend/src/stories/pages/MenuItemReview/MenuItemReviewIndexPage.stories.js, frontend/src/tests/pages/MenuItemReview/MenuItemReviewIndexPage.test.js
Closes issue #41. Tested and working. Published storybook in comment below.
=> Vp menu item reviews index page

frontend/src/App.js, frontend/src/fixtures/recommendationRequestFixtures.js, frontend/src/main/components/RecommendationRequests/RecommendationRequestForm.js, frontend/src/main/pages/RecommendationRequests/RecommendationRequestCreatePage.js, frontend/src/stories/pages/RecommendationRequests/RecommendationRequestCreatePage.stories.js, frontend/src/tests/pages/RecommendationRequests/RecommendationRequestCreatePage.test.js
closes #31 
storybook link: https://6726c65fac869bba81d3d68d-uteinirqwl.chromatic.com/
=> Added Create Page for Recommendation Request

frontend/src/App.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js, frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js, frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js, frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
=> rg - added placeholders

frontend/src/main/pages/HelpRequest/HelpRequestCreatePage.js, frontend/src/main/utils/HelpRequestUtils.js, frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js, frontend/src/tests/components/HelpRequests/HelpRequestTable.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js, frontend/src/tests/utils/HelpRequestUtils.test.js
Navigate to /helprequest/create endpont
Ensure error messages are displayed
Fill out with test data and hit create
Ensure that the proper message shows in the top right
Ensure that new entry shows in the backend
Closes Issue #40
=> rg - finished create page

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java
=> Added Integration Test for RecommendationRequest

src/test/java/edu/ucsb/cs156/example/integration/RecommendationRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/RecommendationRequestWebIT.java
=> Adds End to End tests for RecommendationRequest

frontend/src/main/pages/HelpRequest/HelpRequestIndexPage.js, frontend/src/stories/components/HelpRequests/HelpRequestTable.stories.js, frontend/src/stories/pages/HelpRequest/HelpRequestCreatePage.stories.js, frontend/src/stories/pages/HelpRequest/HelpRequestIndexPage.stories.js, frontend/src/tests/pages/HelpRequest/HelpRequestIndexPage.test.js
Closes issue #50 
https://6726c65fac869bba81d3d68d-kddrglhhkm.chromatic.com/?path=/docs/pages-helprequest-helprequestindexpage--docs
=> rg - added Index page

frontend/src/App.js, frontend/src/main/components/HelpRequests/HelpRequestTable.js, frontend/src/main/components/Nav/AppNavbar.js, frontend/src/main/pages/HelpRequest/HelpRequestEditPage.js, frontend/src/stories/pages/HelpRequest/HelpRequestEditPage.stories.js, frontend/src/tests/components/HelpRequests/HelpRequestTable.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestCreatePage.test.js, frontend/src/tests/pages/HelpRequest/HelpRequestEditPage.test.js
Closes Issue #51 
Edit button implemented
https://6726c65fac869bba81d3d68d-wwaiuimpiq.chromatic.com/?path=/docs/pages-helprequest-helprequesteditpage--docs
=> rg - implemented edit

src/test/java/edu/ucsb/cs156/example/integration/UCSBOrganizationIT.java
Uhh this resolves #119. Also I think I worded the issues incorrectly, my apologies!
=> Finished IT for UCSBOrganizations - 2 IT Tests Completed

README.md, frontend/public/mockServiceWorker.js, src/test/java/edu/ucsb/cs156/example/integration/ArticleIT.java, src/test/java/edu/ucsb/cs156/example/integration/UCSBOrganizationIT.java, src/test/java/edu/ucsb/cs156/example/web/ArticleWebIT.java, src/test/java/edu/ucsb/cs156/example/web/UCSBOrganizationWebIT.java
Finished End to End and integration tests. 
files:
ArticleWebIT.java
ArticleIT.java
=> Team03 billybobjoe123

frontend/public/mockServiceWorker.js, src/test/java/edu/ucsb/cs156/example/integration/HelpRequestIT.java, src/test/java/edu/ucsb/cs156/example/web/HelpRequestWebIT.java
=> Rg help request e2e
